final_project/home/annarborfoodie/final_project/mysite/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
]

final_project/home/annarborfoodie/final_project/mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('restaurants/', include('restaurants.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

# media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

final_project/home/annarborfoodie/final_project/mysite/restaurants/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='restaurants'
urlpatterns = [
    path('', views.ResListView.as_view(), name='all'), # All restaurants as a list view
    path('category/<category>', views.CatListView.as_view(), name="res_category"),
    # CRUD
    path('res/<int:pk>', views.ResDetailView.as_view(), name='res_detail'),
    path('res/create',
        views.ResCreateView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_create'),
    path('res/<int:pk>/update',
        views.ResUpdateView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_update'),
    path('res/<int:pk>/delete',
        views.ResDeleteView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_delete'),
    # comment
    path('res/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='res_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_comment_delete'),
    # favorites
    path('res/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='res_favorite'),
    path('res/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='res_unfavorite'),
    path('myfav', views.FavListView.as_view(), name="my_fav"),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

final_project/home/annarborfoodie/final_project/mysite/home/models.py
from django.db import models

# Create your models here.

final_project/home/annarborfoodie/final_project/mysite/home/views.py
from django.shortcuts import render
from django.views import View
from restaurants.models import Restaurant

class HomeView(View):
    def get(self, request):
        suggested_res = Restaurant.objects.order_by('-rating')[:4]
        ctx = {'restaurants': suggested_res}
        return render(request, 'home/main.html', ctx)

final_project/home/annarborfoodie/final_project/mysite/home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="83da7c539e1ab4e759623c38d8737e9e">

<meta name="dj4e-code" content="42160448232426">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2020-10-23">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

final_project/home/annarborfoodie/final_project/mysite/home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">
            <span style="color:deepskyblue">Ann Arbor</span>
            <span style="color:darkorange">Foodie</span></a>
    </div>

    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                Category<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'restaurants:all' %}category/Burgers">Burgers</a></li>
                <li><a href="{% url 'restaurants:all' %}category/Japanese">Japanese</a></li>
                <li><a href="{% url 'restaurants:all' %}category/Italian">Italian</a></li>
                <li><a href="{% url 'restaurants:all' %}category/Chinese">Chinese</a></li>
                <li><a href="{% url 'restaurants:all' %}category/Mexican">Mexican</a></li>
                <li><a href="{% url 'restaurants:all' %}category/Thai">Thai</a></li>
                <li><a href="{% url 'restaurants:all' %}category/Cafe">Cafe</a></li>
            </ul>
        </li>
        <li>
        <a href="{% url 'restaurants:all' %}">Restaurant List</a>
        </li>
        {% if user.is_authenticated %}
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'restaurants:my_fav' %}">My Favorites</a></li>
                <li><a href="{% url 'logout' %}?next={% url 'home:all' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'home:all' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}