final_project/home/annarborfoodie/final_project/mysite/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
]

final_project/home/annarborfoodie/final_project/mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('restaurants/', include('restaurants.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

# media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

final_project/home/annarborfoodie/final_project/mysite/restaurants/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='restaurants'
urlpatterns = [
    path('', views.ResListView.as_view(), name='all'), # All restaurants as a list view
    path('category/<category>', views.CatListView.as_view(), name="res_category"),
    # CRUD
    path('res/<int:pk>', views.ResDetailView.as_view(), name='res_detail'),
    path('res/create',
        views.ResCreateView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_create'),
    path('res/<int:pk>/update',
        views.ResUpdateView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_update'),
    path('res/<int:pk>/delete',
        views.ResDeleteView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_delete'),
    # comment
    path('res/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='res_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_comment_delete'),
    # favorites
    path('res/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='res_favorite'),
    path('res/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='res_unfavorite'),
    path('myfav', views.FavListView.as_view(), name="my_fav"),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

final_project/home/annarborfoodie/final_project/mysite/restaurants/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.conf import settings


class Category(models.Model) :
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "name must be greater than 2 characters")]
    )
    def __str__(self):
        return self.name


class Price(models.Model) :
    value = models.CharField(
            max_length=4,
            validators=[MinLengthValidator(1, "value: $ $$ $$$ $$$$")]
    )
    def __str__(self):
        return self.value


class Tag(models.Model) :
    name = models.CharField(
            max_length=20,
            validators=[MinLengthValidator(2, "name must be greater than 2 characters")]
    )
    def __str__(self):
        return self.name


class Restaurant(models.Model) :
    name = models.CharField(
            max_length=20,
            validators=[MinLengthValidator(2, "Name must be greater than 2 characters")]
    )
    description = models.TextField(null=True, blank=True)
    location = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Location must be greater than 2 characters")],
            blank=True
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='sub_res')
    tag1 = models.ForeignKey(Tag, on_delete=models.SET_NULL, null=True, blank=True, related_name='tag_1')
    tag2 = models.ForeignKey(Tag, on_delete=models.SET_NULL, null=True, blank=True, related_name='tag_2')
    tag3 = models.ForeignKey(Tag, on_delete=models.SET_NULL, null=True, blank=True, related_name='tag_3')
    rating = models.IntegerField(
             validators=[MinValueValidator(0, "rating >= 0"),
             MaxValueValidator(10, "rating <= 10")])
    price = models.ForeignKey(Price, on_delete=models.SET_NULL, null=True, blank=True)
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Comment', related_name='res_comments')

    # pictures
    pic1 = models.ImageField(upload_to='images/')
    pic2 = models.ImageField(upload_to='images/')
    pic3 = models.ImageField(upload_to='images/')

    # Favorites
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Fav', related_name='favorite_restaurants')

    def __str__(self):
        return self.name


class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'


class Fav(models.Model) :
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('restaurant', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.restaurant.title[:10])

final_project/home/annarborfoodie/final_project/mysite/restaurants/forms.py
from django import forms
from restaurants.models import Restaurant
from django.core.files.uploadedfile import InMemoryUploadedFile
from restaurants.humanize import naturalsize

# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)


# Create the form class.
# class CreateForm(forms.ModelForm):
#     max_upload_limit = 2 * 1024 * 1024
#     max_upload_limit_text = naturalsize(max_upload_limit)

#     # Call this 'picture' so it gets copied from the form to the in-memory model
#     # It will not be the "bytes", it will be the "InMemoryUploadedFile"
#     # because we need to pull out things like content_type
#     picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
#     upload_field_name = 'picture'

#     class Meta:
#         model = Restaurant
#         fields = ['name', 'description',  'location', 'category', 'tag1', 'tag2', 'tag3', 'rating', 'price']

#     # Validate the size of the picture
#     def clean(self):
#         cleaned_data = super().clean()
#         pic = cleaned_data.get('picture')
#         if pic is None:
#             return
#         if len(pic) > self.max_upload_limit:
#             self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

#     # Convert uploaded File object to a picture
#     def save(self, commit=True):
#         instance = super(CreateForm, self).save(commit=False)

#         # We only need to adjust picture if it is a freshly uploaded file
#         f = instance.picture   # Make a copy
#         if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
#             bytearr = f.read()
#             instance.content_type = f.content_type
#             instance.picture = bytearr  # Overwrite with the actual image data

#         if commit:
#             instance.save()

#         return instance

final_project/home/annarborfoodie/final_project/mysite/restaurants/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q

from restaurants.models import Restaurant, Comment, Category, Fav
from restaurants.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from restaurants.forms import CommentForm


class FavListView(OwnerListView):
    model = Restaurant
    # By convention:
    template_name = "restaurants/res_list.html"

    def get(self, request):
        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_restaurants.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]
        my_fav = Restaurant.objects.filter(id__in=favorites)
        context = {'res_list': my_fav}
        return render(request, self.template_name, context)


class CatListView(OwnerListView):
    model = Restaurant
    # By convention:
    template_name = "restaurants/res_list.html"
    context_object_name = 'res_list'

    def get_queryset(self):
        self.cat = get_object_or_404(Category, name=self.kwargs['category'])
        return Restaurant.objects.filter(category=self.cat)


class ResListView(OwnerListView):
    model = Restaurant
    # By convention:
    template_name = "restaurants/res_list.html"

    def get(self, request) :
        res_list = Restaurant.objects.all()
        # favorites = list()
        # if request.user.is_authenticated:
        #     # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
        #     rows = request.user.favorite_ads.values('id')
        #     # favorites = [2, 4, ...] using list comprehension
        #     favorites = [ row['id'] for row in rows ]

        strval = request.GET.get("search", False)
        if strval:
            # Multi-field search
            query = Q(name__contains=strval)
            query.add(Q(location__contains=strval), Q.OR)
            query.add(Q(description__contains=strval), Q.OR)
            res_list = Restaurant.objects.filter(query).select_related().order_by('-rating')[:10]

        ctx = {'res_list' : res_list}
        return render(request, self.template_name, ctx)


class ResDetailView(OwnerDetailView):
    model = Restaurant
    template_name = "restaurants/res_detail.html"
    def get(self, request, pk) :
        x = Restaurant.objects.get(id=pk)
        comments = Comment.objects.filter(restaurant=x).order_by('-updated_at')
        comment_form = CommentForm()

        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_restaurants.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]

        context = {'restaurant': x, 'comments': comments, 'comment_form': comment_form, 'favorites': favorites}
        return render(request, self.template_name, context)


# class ResCreateView(LoginRequiredMixin, View):
class ResCreateView(OwnerCreateView):
    model = Restaurant
    template_name = 'restaurants/res_form.html'
    success_url = reverse_lazy('restaurants:all')
    fields = ['name', 'description',  'location', 'category', 'tag1', 'tag2', 'tag3', 'rating', 'price', 'pic1', 'pic2', 'pic3']


# class ResUpdateView(LoginRequiredMixin, View):
class ResUpdateView(OwnerUpdateView):
    model = Restaurant
    template_name = 'restaurants/res_form.html'
    success_url = reverse_lazy('restaurants:all')
    fields = ['name', 'description',  'location', 'category', 'tag1', 'tag2', 'tag3', 'rating', 'price', 'pic1', 'pic2', 'pic3']


class ResDeleteView(OwnerDeleteView):
    model = Restaurant
    template_name = 'restaurants/res_confirm_delete.html'
    success_url = reverse_lazy('restaurants:all')


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        res = get_object_or_404(Restaurant, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, restaurant=res)
        comment.save()
        return redirect(reverse('restaurants:res_detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "restaurants/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        res = self.object.restaurant
        return reverse('restaurants:res_detail', args=[res.id])


@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        t = get_object_or_404(Restaurant, id=pk)
        fav = Fav(user=request.user, restaurant=t)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        t = get_object_or_404(Restaurant, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, restaurant=t).delete()
        except Fav.DoesNotExist as e:
            pass

        return HttpResponse()

final_project/home/annarborfoodie/final_project/mysite/restaurants/templates/restaurants/comment_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'restaurants:res_detail' comment.restaurant.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

final_project/home/annarborfoodie/final_project/mysite/restaurants/templates/restaurants/res_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Restaurant</h1>

<p>Are you sure you want to delete the restaurant: {{ restaurant }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

final_project/home/annarborfoodie/final_project/mysite/restaurants/templates/restaurants/res_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% load app_tags %}
{% block head %}
<style>
    .background_settings{
        position:fixed;
        top: 0;
        left: 0;
        width:100%;
        height:100%;
        min-width: 1000px;
        z-index:-10;
        zoom: 1;
        background-color: #fff;
        background: url(../../../../media/images/background_img.png);
        background-repeat: no-repeat;
        background-size: cover;
        -webkit-background-size: cover;
        -o-background-size: cover;
        background-position: center 0;
    }

    .flex-container{
        display: flex;
        flex-flow: row wrap;
        justify-content: flex-start;
        padding: 0;
        margin: 0;
        list-style: none;
    }

    .flex-item{
        background: rgba(0, 128, 0, 0.3);
        width: 100%;
        /*display:table-cell;*/
        height: auto;
        margin-top: 5px;
        margin-left: 0;
        margin-right: 10px;
        padding: 0px 15px 15px 15px;
        color: black;
        font-family: "Gill Sans", sans-serif;
        font-size: 1.5em;
        font-weight: bold;
        line-height: 180%;
        /*text-align: center;*/
        overflow: auto;
    }

    /* unvisited link */
    a:link {
        color: darkorange;
    }
    /* visited link */
    a:visited {
        color: darkmagenta;
    }
    /* mouse over link */
    a:hover {
        color: deeppink;
        text-decoration: none;
    }
    /* selected link */
    a:active {
        color: #800000;
    }
</style>
{% endblock %}

{% block content %}
<div class="background_settings"></div>
<div>
    <div>
        <img src="{{ restaurant.pic1.url}}" alt="NoImage" style="margin-left:0;margin-right:0.5%;width:32%;height:auto;border:2px solid green">
        <img src="{{ restaurant.pic2.url}}" alt="NoImage" style="margin-left:0;margin-right:0.5%;width:32%;height:auto;border:2px solid green">
        <img src="{{ restaurant.pic3.url}}" alt="NoImage" style="margin-left:0;margin-right:0;width:32%;height:auto;border:2px solid green">
    </div>

    <div class="flex-item">
        <br>
        <span style="font-size:2em;">{{restaurant.name}}</span> &nbsp &nbsp
        {% if user.is_authenticated %}
        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <a href="#" onclick=
            "favPost('{% url 'restaurants:res_unfavorite' restaurant.id %}', {{ restaurant.id }} );return false;"
            {% if restaurant.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{restaurant.id}}">
            <span class="fa-stack" style="vertical-align:middle; font-size:2em; float:right;">
                <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                <i class="fa fa-star-o fa-stack-1x"></i>
            </span>
        </a>
        <!-- the second href -->
        <a href="#" onclick=
             "favPost('{% url 'restaurants:res_favorite' restaurant.id %}', {{ restaurant.id }} );return false;"
            {% if restaurant.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{restaurant.id}}">
            <span class="fa-stack" style="vertical-align:middle; font-size:2em; float:right;">
                <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                <i class="fa fa-star-o fa-stack-1x"></i>
            </span>
        </a>
        {% endif %}
        <br>
        <span style="font-size:0.8em; font-style:italic; color:grey;">{{ restaurant.description }}</span><br>
        <span style="color:red;">
            <script>
                var a = Math.floor({{restaurant.rating}} / 2);
                var b = {{restaurant.rating}} % 2;
                var i;
                for (i=0; i<a; i++){
                    document.write('<i class="fa fa-star" aria-hidden="true"></i>');
                }
                if (b){
                    document.write('<i class="fa fa-star-o" aria-hidden="true"></i>');
                }
            </script>
        </span><br>
        <span style="color:black;">{{restaurant.price}}&nbsp &middot &nbsp{{restaurant.category}}</span><br>
        <span style="font-size:0.8em; color:dimgrey;">{{restaurant.location}}</span><br>
        <span style="font-size:0.8em; color:black;">
            {% if restaurant.tag1 %}<i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>{{restaurant.tag1}}{% endif %}&nbsp
            {% if restaurant.tag2 %}<i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>{{restaurant.tag2}}{% endif %}&nbsp
            {% if restaurant.tag3 %}<i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>{{restaurant.tag3}}{% endif %}&nbsp
        </span>
        <br>
        {% if restaurant.owner == user %}
        <div style="padding:10px;">
            <a href="{% url 'restaurants:res_update' restaurant.id %}"><i class="fa fa-pencil" style="font-size:30px;color:blue;"></i></a> &nbsp
            <a href="{% url 'restaurants:res_delete' restaurant.id %}"><i class="fa fa-trash" style="font-size:30px;color:red;"></i></a>
        </div>
        {% endif %}

    </div>


</div>

{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'restaurants:res_comment_create' restaurant.id %}" style="width:60%;">
    {% csrf_token %}
    {{ comment_form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Back to restaurant list" onclick="window.location.href='{% url 'restaurants:all' %}';return false;">
</form>
</p>
{% endif %}
<br>
{% for comment in comments %}
<p style="font-size: 20px; font-family: system-ui;">
    <img style="width: 25px;" src="{{ comment.owner|gravatar:60 }}"/>
    <span style="font-weight:bold;">{{comment.owner}}: &nbsp</span>
    {{ comment.text }}
    <span style="font-size: 15px; font-family: system-ui; font-style:italic;">
        &nbsp &nbsp (posted {{ comment.updated_at|naturaltime }}) &nbsp &nbsp
    </span>
    {% if user == comment.owner %}
    <a href="{% url 'restaurants:res_comment_delete' comment.id %}"><i class="fa fa-trash" style="color:red;"></i></a>
    {% endif %}
    <hr width=100% style="border:1px dashed grey; height:1px;">
</p>
{% endfor %}

<script>
function favPost(url, ad_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+ad_id).toggle();
        $("#favorite_star_"+ad_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}

final_project/home/annarborfoodie/final_project/mysite/restaurants/templates/restaurants/res_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'restaurants:all' %}';return false;">
  </form>
</p>

{% endblock %}

final_project/home/annarborfoodie/final_project/mysite/restaurants/templates/restaurants/res_list.html
{% extends "base_menu.html" %}

{% block head %}
<style>
    .background_settings{
        position:fixed;
        top: 0;
        left: 0;
        width:100%;
        height:100%;
        min-width: 1000px;
        z-index:-10;
        zoom: 1;
        background-color: #fff;
        background: url(../../../../media/images/background_img.png);
        background-repeat: no-repeat;
        background-size: cover;
        -webkit-background-size: cover;
        -o-background-size: cover;
        background-position: center 0;
    }

    h1{
        font-weight: bold;
        color: tomato;
        font-size: 30px;
        font-family: Comic Sans MS, Comic Sans, cursive;
        display: block;
        text-align: center;
        margin-top: 1em;
        margin-bottom: 0.5em;
    }

    .button_settings{
        font-weight: bold;
        color: white;
        font-size: 20px;
        font-family: Comic Sans MS, Comic Sans, cursive;
        display: block;
        text-align: center;
        background-color: skyblue;
        margin-top:0.5em;
        margin-bottom: 0.5em;
    }

    .flex-container{
        display: flex;
        flex-flow: row wrap;
        justify-content: space-around;
        padding: 0;
        margin: 0;
        list-style: none;
    }

    .flex-item{
        background: rgba(175, 238, 238, 0.5);
        width: 540px;
        height: 290px;
        margin-top: 20px;
        color: black;
        font-family: "Gill Sans", sans-serif;
        font-size: 1.5em;
        line-height: 180%;
        /*text-align: center;*/
        overflow: auto;
    }

    .img_settings{
        display: block;
        width:200px;
        height:auto;
        float: left;
        margin-top: 10px;
        margin-left: 10px;
    }

    /* unvisited link */
    a:link {
        color: black;
    }
    /* visited link */
    a:visited {
        color: darkmagenta;
    }
    /* mouse over link */
    a:hover {
        color: deeppink;
        text-decoration: none;
    }
    /* selected link */
    a:active {
        color: #800000;
    }
</style>
{% endblock %}

{% block content %}
<div class="background_settings"></div>
{% if user.is_authenticated %}
<a href="{% url 'restaurants:res_create' %}" class="button_settings">Add a Restaurant</a>
{% endif %}
<h1>Restaurant List</h1>
<p>
{% if res_list %}
<ul class="flex-container">
  {% for res in res_list %}
    <li class="flex-item">
        <a href="{% url 'restaurants:res_detail'  res.id %}">
            <img src="{{ res.pic1.url}}" alt="NoImage" class="img_settings">
            <p style="float:left; width:320px; padding-left:10px; padding-top:10px;">
                <span style="font-weight:bold; font-size:1.5em;">{{res.name}}</span><br>
                <span style="color:red;">
                    <script>
                        var a = Math.floor({{res.rating}} / 2);
                        var b = {{res.rating}} % 2;
                        var i;
                        for (i=0; i<a; i++){
                            document.write('<i class="fa fa-star" aria-hidden="true"></i>');
                        }
                        if (b){
                            document.write('<i class="fa fa-star-o" aria-hidden="true"></i>');
                        }
                    </script>
                </span><br>
                <span style="color:black;">{{res.price}}&nbsp &middot &nbsp{{res.category}}</span><br>
                <span style="font-size:0.8em; color:dimgrey;">{{res.location}}</span><br>
                <span style="font-size:0.8em; color:black;">
                    {% if res.tag1 %}<i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>{{res.tag1}}{% endif %}
                    {% if res.tag2 %}<i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>{{res.tag2}}{% endif %}
                    {% if res.tag3 %}<i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>{{res.tag3}}{% endif %}
                </span><br>
                {% if res.owner == user %}
                <span style="font-size:0.8em; color:black;">
                    <a href="{% url 'restaurants:res_update' res.id %}"><i class="fa fa-pencil" style="font-size:20px;color:blue;"></i></a> &nbsp
                    <a href="{% url 'restaurants:res_delete' res.id %}"><i class="fa fa-trash" style="font-size:20px;color:red;"></i></a>
                </span>
                {% endif %}
            </p>
        </a>
    </li>
  {% endfor %}
</ul>
{% else %}
<p style="color:black; font-size: 20px; font-family:Comic Sans MS,Comic Sans,cursive;">
    No Results...
</p>
{% endif %}
</p>

{% endblock %}