final_project/home/annarborfoodie/final_project/mysite/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
]

final_project/home/annarborfoodie/final_project/mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('restaurants/', include('restaurants.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

# media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

final_project/home/annarborfoodie/final_project/mysite/restaurants/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='restaurants'
urlpatterns = [
    path('', views.ResListView.as_view(), name='all'), # All restaurants as a list view
    path('category/<category>', views.CatListView.as_view(), name="res_category"),
    # CRUD
    path('res/<int:pk>', views.ResDetailView.as_view(), name='res_detail'),
    path('res/create',
        views.ResCreateView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_create'),
    path('res/<int:pk>/update',
        views.ResUpdateView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_update'),
    path('res/<int:pk>/delete',
        views.ResDeleteView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_delete'),
    # comment
    path('res/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='res_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('restaurants:all')), name='res_comment_delete'),
    # favorites
    path('res/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='res_favorite'),
    path('res/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='res_unfavorite'),
    path('myfav', views.FavListView.as_view(), name="my_fav"),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

final_project/home/annarborfoodie/final_project/mysite/home/models.py
from django.db import models

# Create your models here.

final_project/home/annarborfoodie/final_project/mysite/home/views.py
from django.shortcuts import render
from django.views import View
from restaurants.models import Restaurant

class HomeView(View):
    def get(self, request):
        suggested_res = Restaurant.objects.order_by('-rating')[:4]
        ctx = {'restaurants': suggested_res}
        return render(request, 'home/main.html', ctx)

final_project/home/annarborfoodie/final_project/mysite/home/templates/home/main.html
{% extends "base_menu.html" %}
{% load app_tags %}
{% block head %}
<style>
    .background_settings{
        position:fixed;
        top: 0;
        left: 0;
        width:100%;
        height:100%;
        min-width: 1000px;
        z-index:-10;
        zoom: 1;
        background-color: #fff;
        background: url(../../../../media/images/background_img.png);
        background-repeat: no-repeat;
        background-size: cover;
        -webkit-background-size: cover;
        -o-background-size: cover;
        background-position: center 0;
    }

    h1{
        font-weight: bold;
        color: #fff;
        font-size: 50px;
        font-family: Comic Sans MS, Comic Sans, cursive;
        display: block;
        text-align: center;
        margin-top: 2.5em;
        margin-bottom: 1em;
    }

    h2{
        font-weight: bold;
        color: #fa8072;
        font-size: 30px;
        font-family: Brush Script MT, Brush Script Std, cursive;
        display: block;
        text-align: center;
        /*margin-top: 0;*/
        margin-left: auto;
        margin-right: auto;
        padding: 10px;
    }

    div.a{
        width: 98%;
        height: 750px;
        background: rgba(0, 128, 0, 0.3);
        margin-left: auto;
        margin-right: auto;
        margin-top: 50px;
        margin-bottom: 0;
        /*border: 15px solid green;*/
    }

    .flex-container{
        display: flex;
        flex-flow: row wrap;
        justify-content: space-around;
        padding: 0;
        margin: 0;
        list-style: none;
    }

    .flex-item{
        background: rgba(250,250,210,0.8);
        width: 540px;
        height: 290px;
        margin-top: 20px;
        color: black;
        font-family: "Gill Sans", sans-serif;
        font-size: 1.5em;
        line-height: 180%;
        /*text-align: center;*/
        overflow: auto;
    }

    .img_settings{
        display: block;
        width:200px;
        height:auto;
        float: left;
        margin-top: 10px;
        margin-left: 10px;
    }

    /* unvisited link */
    a:link {
        color: black;
    }
    /* visited link */
    a:visited {
        color: darkmagenta;
    }
    /* mouse over link */
    a:hover {
        color: deeppink;
        text-decoration: none;
    }
    /* selected link */
    a:active {
        color: #800000;
    }

    .search_container{
        display: flex;
        flex-flow: row wrap;
        justify-content: space-around;
        padding: 0;
        margin: 0;
        list-style: none;
    }

    .search_block{
        display: block;
        /*border: 5px solid green;*/
        width: 50%;
        height: 50px;
        font-size: 25px;
        padding: auto;
        background-color: white;
        margin-left: 25%;
        margin-right: 5px;
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .button_settings{
        display: block;
        width:50px;
        height:50px;
        font-size: 30px;
        margin-left:0;
        margin-right:5px;
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .undo_settings{
        display: block;
        width:50px;
        height:50px;
        font-size: 30px;
        margin-left:0;
        margin-right:auto;
        margin-top: 20px;
        margin-bottom: 20px;
        float: left;
        line-height:50px;
    }
</style>
{% endblock %}

{% block content %}
<div class="background_settings"></div>
<h1>
    <span style="color:deepskyblue">Ann Arbor</span>
    <span style="color:darkorange">Foodie</span>
</h1>
<div>
    <form action="{% url 'restaurants:all' %}" class="search_container">
        <input type="text" placeholder="Search.." name="search"  class="search_block"
        {% if search %} value="{{ search }}" {% endif %}
        >
        <button type="submit" class="button_settings"><i class="fa fa-search"></i></button>
        <a href="{% url 'home:all' %}" class="undo_settings"><i class="fa fa-undo"></i></a>
    </form>
</div>
<div class="a">
    <h2>Suggestions</h2>
    <ul class="flex-container">
        {% for res in restaurants %}
        <li class="flex-item">
            <a href="{% url 'restaurants:res_detail'  res.id %}">
                <img src="{{ res.pic1.url}}" alt="NoImage" class="img_settings">
                <p style="float:left; width:320px; padding-left:10px; padding-top:10px;">
                    <span style="font-weight:bold; font-size:1.5em;">{{res.name}}</span><br>
                    <span style="color:red;">
                        <script>
                            var a = Math.floor({{res.rating}} / 2);
                            var b = {{res.rating}} % 2;
                            var i;
                            for (i=0; i<a; i++){
                                document.write('<i class="fa fa-star" aria-hidden="true"></i>');
                            }
                            if (b){
                                document.write('<i class="fa fa-star-o" aria-hidden="true"></i>');
                            }
                        </script>
                    </span><br>
                    <span style="color:black;">{{res.price}}&nbsp &middot &nbsp{{res.category}}</span><br>
                    <span style="font-size:0.8em; color:dimgrey;">{{res.location}}</span><br>
                    <span style="font-size:0.8em; color:black;">
                        {% if res.tag1 %}<i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>{{res.tag1}}{% endif %}
                        {% if res.tag2 %}<i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>{{res.tag2}}{% endif %}
                        {% if res.tag3 %}<i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>{{res.tag3}}{% endif %}
                    </span><br>
                </p>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}